### ISSUE TITLE
Steno.fm

### ISSUE THREAD

**Issue by nathangathright** [Podcast-Standards-Project/Certification#1]
|  | Response |
| --- | --- |
| Name | Steno.fm |
| Logo | ![Steno.fm logo Dark Mode](https://raw.githubusercontent.com/StenoFM/brandassets/main/wordmark_white-text.svg#gh-dark-mode-only) ![Steno.fm logo Light Mode](https://raw.githubusercontent.com/StenoFM/brandassets/main/wordmark_black-text.svg#gh-light-mode-only) [Brand Assets](https://github.com/StenoFM/brandassets) |
| Category | Podcast Player |
| Description | A podcast app designed with first-class support for transcripts |
| Contact | hello@steno.fm, [@stenofm@podcastindex.social](https://podcastindex.social/@stenofm), [twitter.com/stenofm](https://twitter.com/stenofm) |
| Supports `<podcast:transcript>` | [![CleanShot 2023-03-28 at 15 44 48](https://user-images.githubusercontent.com/3632071/228363027-9a2bc8fe-c225-4a95-a2d1-ef8bc9188c3b.gif)](https://www.steno.fm/show/7d1a25c1-c5d2-540b-95eb-ba83ec2521de/episode/QnV6enNwcm91dC0yNTYyODIz) |
| Supports `<podcast:funding>` | [![CleanShot 2023-03-28 at 15 46 33@2x](https://user-images.githubusercontent.com/3632071/228363446-9a3ba1e4-ba4a-46b0-a3cd-824bf2d8eda6.png)](https://www.steno.fm/show/778116ac-6b1e-5ae2-b037-26a7ff2aee64) |

Images are linked to the corresponding web pages to demonstrate element support.

**Comment by snookfin** [comment]
@nathangathright Everything looks great. Approving this certification and have added the Steno logo to the podstandards.org website. Feel free to grab a PSP Certified badge and add it to your site.

Thank you!
