### ISSUE TITLE
Podfans Certification Application

### ISSUE THREAD

**Issue by samsethi** [Podcast-Standards-Project/Certification#2]
**The name of your product/service:** 
Podfans

**A link to your logo (vector preferred)**
![logo](https://user-images.githubusercontent.com/3492066/229927410-c8ddf9df-e8eb-49f3-84fe-f930de9f7557.svg)

**Product/service category (hosting, player app, validation, etc.)**
App/Platform

**A short description of your service (one sentence)**
Podfans is a podcasting app where listeners discover the podcasts they love but only pay the price they want for the value they receive. #value4value

**Your contact information (email, twitter)** 
sam@podfans.fm
@joinpodfans

Below are screenshots of our support for Transcriptions and Funding Tags.  

Podcast Funding Tag 
<img width="1166" alt="Podfans___Dashboard" src="https://user-images.githubusercontent.com/3492066/229928635-7fe4c2e9-3236-4344-8db3-a7e4bbb29965.png">

Podcast Transcript Tag
<img width="1146" alt="Podfans___Dashboard" src="https://user-images.githubusercontent.com/3492066/229928445-4eeaa1b8-801d-48e3-9b02-a7294ecf2e9f.png">

If approved can I add the PSP logo to our website and admin dashboard.  Equally will we be added to the PSP website?

**Comment by snookfin** [comment]
Approved. The logo has been added to the podstandard.org homepage.
