### ISSUE TITLE
Podba.se might be incorrectly reporting itunes:explicit

### ISSUE THREAD

**Issue by Agorise** [Podcast-Standards-Project/Certification#8]
Hi @CharlesWiltgen :) 
Podba.se might be incorrectly reporting itunes:explicit at both the channel and item levels. 
 
See one of our rss feeds: 
https://cast.garden/feeds/podcast/videos.xml?videoChannelId=37 
And as reported though on podba.se: 
https://podba.se/?url=https://cast.garden/feeds/podcast/videos.xml?videoChannelId=37

**Comment by Agorise** [comment]
Nevermind, I just realized it is looking for true/false, not yes/no

**Comment by Agorise** [comment]
Also @CharlesWiltgen on the @Marzal Cover Art report on podba.se there is an error on his feed that says: 
![Screenshot from 2023-08-10 10-39-51](https://github.com/Podcast-Standards-Project/Certification/assets/31280836/29c8e46b-0e12-430c-aec5-45ce92499ab2) 
 
I for the life of me could not get a 3000x3000 sized image below 944K (I use tinypng.com too). So, you might want to set your error reporting on podba.se to not show that blue error message above unless the image filesize exceeds 1MB.

**Comment by CharlesWiltgen** [comment]
> *I for the life of me could not get a 3000x3000 sized image below 944K (I use tinypng.com too).*

@Agorise, mind sharing the link so I can see the image?

**Comment by Agorise** [comment]
Hey @CharlesWiltgen :) 
Here's a couple of examples. Please use your favorite compression tool to shrink the filesize on these: 
https://cast.garden/images/t/apple-itunes-images-channel-avatar.png 
https://cast.garden/images/t/apple-itunes-images-channel-avatar.jpg

**Comment by CharlesWiltgen** [comment]
> *It his repo a valid place to ask you another "error" validating a feed?*

Sure, @Marzal! You can also use the chat widget on the validator page to report feed URLs that the validator doesn't handle correctly. [That podcast feed](https://podba.se/?url=https://kdeexpress.gitlab.io/feed_mp3) has an `<item>` element without an `<enclosure>`, which is something I've never seen before (and so have never tested before) in a podcast feed. 

Thank you for taking the trouble to report this, and hopefully it will work for you now. Can you please try again?

**Comment by Marzal** [comment]
> > _It his repo a valid place to ask you another "error" validating a feed?_
> 
> Sure, @Marzal! You can also use the chat widget on the validator page to report feed URLs that the validator doesn't handle correctly. [That podcast feed](https://podba.se/?url=https://kdeexpress.gitlab.io/feed_mp3) has an `<item>` element without an `<enclosure>`, which is something I've never seen before (and so have never tested before) in a podcast feed.
> 
> Thank you for taking the trouble to report this, and hopefully it will work for you now. Can you please try again?

Thanks for the quick update. And also the validator is now more verbose with the errors in https://kdeexpress.gitlab.io/feed, which is the same feed but with ogg files instead of mp3. In this case is in porpuse but verbose is always good 👍

**Comment by CharlesWiltgen** [comment]
> *In this case is in porpuse but verbose is always good* 👍

Is it useful? I'm wondering if I should special case the situation where every `<enclosure>` is using an invalid file extension.

Out of curiosity, why not use a universally supported format for the `<enclosure>` and then use `<podcast:alternateEnclosure>` for others?

**Comment by Marzal** [comment]
> > _In this case is in porpuse but verbose is always good_ +1
> 
> Is it useful? I'm wondering if I should special case the situation where every `<enclosure>` is using an invalid file extension.
I do think that if all the enclosures match the same error it could be summarized
> 
> Out of curiosity, why not use a universally supported format for the `<enclosure>` and then use `<podcast:alternateEnclosure>` for others?
When the first podcast that uses the"[framework](https://gitlab.com/Marzal/hugo-cards-podcast)" to create the feeds was created, mp3 was not yet a free (in a free software sense) codec/Open format, and the podcast that first used is about Linux and Free Software, so ogg was preferred, also we didn't know about `alternateEnclosure` or was not yet approved.
Some podcasters preferred to use 2 enclosures (against the RSS spec) per episode given that most of the apps fallback to mp3 (the second one) if they don't support ogg. Others just create 2 feeds (one with ogg and one with mp3 for Apple).

`<podcast:alternateEnclosure>` is not yet enough [supported](https://podcastindex.org/apps?appTypes=open+source&elements=Alternate+Enclosure) , but I will add it as soon as I have the time as is the correct/canonical way to go.

TL:NR
GNU/Linux communities/podcaster are sometimes a bit special/"purist" and it just works most of the time :rofl:

**Comment by Marzal** [comment]
@CharlesWiltgen also I found why I didn't find the chat widget on the validator, it's blocked by default with uBlock Origin :sweat_smile: 

![imagen](https://github.com/Podcast-Standards-Project/Certification/assets/2069735/f9a270b8-5a21-4708-886a-f0f795b9bc9e)
